# Generated by Django 5.1.1 on 2025-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_students', models.IntegerField()),
                ('new_students', models.IntegerField()),
                ('graduating_students', models.IntegerField()),
                ('retention_rate', models.FloatField()),
            ],
        ),
    ]
